### ISSUE TITLE
GUI issue

### ISSUE THREAD

**Issue by andrewvictor** [OctoPrint/OctoPrint-CuraEngineLegacy#11]
This may be an isolated issue, nonetheless, after most recent OctoPrint update, the layout is now distorted.
Chrome Version 87.0.4280.141, RPi3
Thanks!
![image](https://user-images.githubusercontent.com/23705107/105407203-042a6580-5bf3-11eb-9447-45b6188f63bf.png)

**Comment by foosel** [comment]
Wrong plugin. Your screenshot is https://plugins.octoprint.org/plugins/slicer/, this plugin here doesn't even have a frontend.
