### ISSUE TITLE
Where is the bridge code between frontend and backend

### ISSUE THREAD

**Issue by cemakpolat** [OctoPrint/OctoPrint-CuraEngineLegacy#2]
Hi, 
I want to provide the functionalites of this plugin as rest-api, however, I couldn't see the bridge code betewen front end and python code that calls the slice operation. My goal is simply to do the slice without using the plugin interface. 

best regards,
Cem

**Comment by foosel** [comment]
This plugin integrates with OctoPrint's built-in slicing plugin infrastructure which takes care of providing [an API for it](http://docs.octoprint.org/en/master/api/slicing.html).

**Comment by cemakpolat** [comment]
This API does provide only listing/adding/removing the slice profiles, it doesn't start the slicing operation. I found now, slice operation is given under file operations :). Now, I can understand how all works together. Thank you!

**Comment by foosel** [comment]
Ah sorry, misremembered that myself. Glad you found it though.
