### ISSUE TITLE
How do i use it ?

### ISSUE THREAD

**Issue by Shine6Z** [OctoPrint/OctoPrint-CuraEngineLegacy#5]
I have configured the slice parameters, but I don't know how to use it.

**Comment by foosel** [comment]
Upload an STL, then use the little wand to slice. For further questions regarding OctoPrint's slicing workflow please ask on the [Community Forums](https://community.octoprint.org), this tracker is reserved for bugs :)

**Comment by Shine6Z** [comment]
Ok, thank you. I've got it.
