### ISSUE TITLE
CuraEngine Legacy: 1.1.1 

### ISSUE THREAD

**Issue by ProtomakerSprint** [OctoPrint/OctoPrint-CuraEngineLegacy#6]
Updated via Octoprint BUT not heating bed or nozzle

**Comment by markwal** [comment]
I'm assuming this is a slice gone wrong?  If so, could you put the profile (.ini you imported and/or the .profile file from ~/.octoprint/slicingProfiles/curalegacy), the stl file sliced (a small cube, for example, that shows the problem) and the resulting .gcode file.  Are you using other plugins to orchestrate the slice?

**Comment by markwal** [comment]
I'm closing for now since I don't have enough information to take any action.  Feel free to re-open with further info.
