### ISSUE TITLE
Incompatible with octoprint 1.5(.2)

### ISSUE THREAD

**Issue by danielvandenberg95** [OctoPrint/OctoPrint-CuraEngineLegacy#9]
![image](https://user-images.githubusercontent.com/8654023/104322998-e750ac80-54e5-11eb-8417-1527190bbc90.png)
The user interface became unusable when I updated from octoprint 1.4(.?) to 1.5.2.

**Comment by foosel** [comment]
Wrong plugin. That's https://plugins.octoprint.org/plugins/slicer/. 

CuraEngineLegacy doesn't have anything but a settings dialog.
